[debug] [2020-04-30T03:39:45.523Z] ----------------------------------------------------------------------
[debug] [2020-04-30T03:39:45.525Z] Command:       /usr/bin/node /usr/bin/firebase init
[debug] [2020-04-30T03:39:45.526Z] CLI Version:   8.0.2
[debug] [2020-04-30T03:39:45.526Z] Platform:      linux
[debug] [2020-04-30T03:39:45.526Z] Node Version:  v10.20.1
[debug] [2020-04-30T03:39:45.526Z] Time:          Thu Apr 30 2020 04:39:45 GMT+0100 (Central European Standard Time)
[debug] [2020-04-30T03:39:45.526Z] ----------------------------------------------------------------------
[debug] [2020-04-30T03:39:45.526Z] 
[debug] [2020-04-30T03:39:45.535Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-30T03:39:45.567Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/usr/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:160:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2020-04-30T03:39:49.758Z] ----------------------------------------------------------------------
[debug] [2020-04-30T03:39:49.760Z] Command:       /usr/bin/node /usr/bin/firebase init
[debug] [2020-04-30T03:39:49.760Z] CLI Version:   8.0.2
[debug] [2020-04-30T03:39:49.761Z] Platform:      linux
[debug] [2020-04-30T03:39:49.761Z] Node Version:  v10.20.1
[debug] [2020-04-30T03:39:49.761Z] Time:          Thu Apr 30 2020 04:39:49 GMT+0100 (Central European Standard Time)
[debug] [2020-04-30T03:39:49.761Z] ----------------------------------------------------------------------
[debug] [2020-04-30T03:39:49.761Z] 
[debug] [2020-04-30T03:39:49.770Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-04-30T03:39:49.803Z] Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/usr/lib/node_modules/firebase-tools/node_modules/google-auth-library/build/src/auth/googleauth.js:160:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[error] 
[error] Error: An unexpected error has occurred.
